language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: false
      osx_image: xcode7.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - qt5-default
      - libqt5opengl5-dev
      - xorg-dev
      - lib32stdc++6 # For CMake

cache:
  directories:
    - "$HOME/.local"

install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"

deploy:
  provider: bintray
  file: "${HOME}/build/${TRAVIS_REPO_SLUG}/.travis.descriptor.json"
  user: citra-emu
  key:
    secure: "Hdj+/UyDYbvOOXJdlrV0n//t6tAnUqMEy4+Ppb84aF+na4B2hoc+RQ6rfbVXnFE0YKAKJme0J00GVi4JcXViOil2P/wHWxniWBlpz1vHLPT15+p1qi8cPQ0yKMAq9+1kYe6APkHjjsZxHAR6cf1fckI/rPfx/lyuDQOpVq07pJg="